### ISSUE TITLE
Parse for Italian case counts data and integrate this data into the app

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios_data#2]
We want to have the most up-to-date case counts data.

The case counts for Italy are available at:
https://github.com/pcm-dpc/COVID-19/blob/master/dati-json/dpc-covid19-ita-regioni.json

We need to:
 -  parse this `.json` into our `.tsv` format and load it into the application. The parser tools we typically put into the `tools/` directory
 - be able to update this data as new `.json`files will be published

The data is licensed with CC-BY-4.0

Related:

 - https://github.com/neherlab/covid19_scenarios/issues/22

**Comment by nnoll** [comment]
Result can be found in parsers/italy.py
