### ISSUE TITLE
🇩🇪 Data from Germany

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios_data#21]
@chriswien posted in the https://github.com/neherlab/covid19_scenarios/issues/18#issuecomment-602106287 about the data from Germany

If someone is available, feel free to pick it up.

**Comment by nnoll** [comment]
I'll be happy to take a look tonight or tomorrow morning if no one gets to it by then.

**Comment by CWienbruch** [comment]
Hi,
thanks for your patience and please forget my previous emails. I finnally figured it out.
  
The file creation in the branch chriswien/covid19_scenarios_data does work now.
Directory case-counts/Europe/Western\ Europe/Germany/ must be created first. tsv files are created there.

It's basically the parser/germany.py and the sources.json files which link to a 
https://github.com/chriswien/COVID19_CaseNumberDE.git

I will update those files after stripping data from
RKI or if you like to implement that yourself, I attach rki_get_data.py which strips the table from the 
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html

This table is updated every morning at 10:00 am.

The data table needs to be converted using 
sed -f convert.sed <filename>


Cheers
Christian

> Nicholas Noll <notifications@github.com> hat am 22. März 2020 00:37 geschrieben:
> 
> 
>  
> I'll be happy to take a look tonight or tomorrow morning if no one gets to it by then.
>

**Comment by rneher** [comment]
Thanks!!! 
@chriswien Could you make a PR? I'll get it up as soon as I can.

**Comment by rneher** [comment]
Thanks again. this is closed in PR #25. Data should be up.
