### ISSUE TITLE
🇧🇷 Add Brazil Scenarios

### ISSUE THREAD

**Issue by gstvribs** [neherlab/covid19_scenarios_data#29]
Hi,

I was recently working and trying to bring in the COVID scenarios from Brazil to trying to run the simulate scenarios, the problem in my country is because we do not have any official releases

I see that in repository we already have the CDS parser that gets [data from John Hopkins](https://github.com/CSSEGISandData/COVID-19) and in that dashboard we have data from Brazil, can we work on this issue to add brazil scenario?

Here in south america the country is about to get a collapse in public health in about a month

**Comment by nnoll** [comment]
The Brazil case counts are already loaded into the app using data provided by the ECDC. The only impediment from an addition of a Brazil scenario is we need the requisite fields provided for Brazil in the file populationData.tsv. Would you be interested in tracking down these numbers and contributing?

**Comment by gstvribs** [comment]
yes, for sure!

**Comment by rneher** [comment]
Brazil there. I'll open another issue for regions!
