### ISSUE TITLE
🇨🇦 Add data from Canada

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios_data#36]
Natalia (@nataliadgepi) in https://github.com/neherlab/covid19_scenarios/issues/162 proposed the data from Canada. 

If someone is available, feel free to check it out and start working.

Related:
 - [Data Contibutor's Guide](https://github.com/neherlab/covid19_scenarios_data#contributing-and-curating-data)

**Comment by noleti** [comment]
I'm working on it, will open PR soon

**Comment by nataliadgepi** [comment]
Thank you!!!!

**Comment by rneher** [comment]
@nataliadgepi Do you happen to have a list of all Canadian provinces, their population sizes, and number of hospital/ICU beds? We would need those to include the Canadian provinces into the population presets. They need to go into this table:
https://github.com/neherlab/covid19_scenarios_data/blob/master/populationData.tsv
(don't worry about the importsPerDay and suspectedCaseMarch1st, we generate those with a script.

**Comment by nataliadgepi** [comment]
@rneher I can get a list of Canadian provinces and population sizes, let me look into getting acute care beds and ICU beds, that might be trickier.

**Comment by nataliadgepi** [comment]
@rneher Here is the data, not sure how to add it to your file. 

[CANprovincialdata.txt](https://github.com/neherlab/covid19_scenarios_data/files/4379097/CANprovincialdata.txt)

**Comment by rcbevans** [comment]
> @rneher Here is the data, not sure how to add it to your file.
> 
> [CANprovincialdata.txt](https://github.com/neherlab/covid19_scenarios_data/files/4379097/CANprovincialdata.txt)

I will do that for you now

**Comment by rcbevans** [comment]
I created a PR in the data repo: https://github.com/neherlab/covid19_scenarios_data/pull/49.

There appears to be a problem with your provided data; you didn't provide values for hospital beds and ICU beds for the Northwest Territories.  I left this territory from the PR for now.

**Comment by noleti** [comment]
I found the following, but cannot open the xlsx in libreoffice https://www.cihi.ca/en/covid-19-resources

**Comment by rneher** [comment]
I merged this now but would be good to get back to with updated numbers.

**Comment by noleti** [comment]
I found numbers for NWT in https://www.cihi.ca/sites/default/files/document/icu_datatables_en.xlsx
and added them in https://github.com/neherlab/covid19_scenarios_data/commit/b1112d1cb20705fee72ba37dc69f36f56ee40c54

**Comment by nataliadgepi** [comment]
Amazing.  Thank you.  I was trying to get updated numbers from a source.

**Comment by nataliadgepi** [comment]
There are hospitalization and ICU numbers but they aren't being shared publicly at this point. :(
