### ISSUE TITLE
Directory `aux` breaks Windows

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios_data#39]
With `aux/` it is impossible to clone the repository on Windows (including the app repository, via submodule).

`aux` is a serial (COM) port on Windows :)
https://stackoverflow.com/a/38457713

Also, now that we are on it, can we make the name more descriptive than `auxData`? ;)

Related in the app:
https://github.com/neherlab/covid19_scenarios/issues/3

**Comment by nnoll** [comment]
Changed.
