### ISSUE TITLE
Crowdsource case counts data

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios_data#4]
We want case counts data to be updated often, as the situation in the world evolves.

We need to:
 * have a dedicated directory (say, `data/case-counts/`) or even repository for this data 
 * put data into `.tsv` files per location (country, city, etc.): `data/case-counts/<region>.tsv` e.g. `data/case-counts/CH-Basel-Stadt.tsv`.
 * these `.tsv` files will contain the following columns:

    ```tsv
      date  cases  deaths  hosptitalized ICU recovered
      2020-03-14 ...
    ```
 * accept pull requests for updates and additions to the data
 * have a set of scripts to convert the incoming data in different formats into our `.tsv` format
 * assign a maintainer to retrieve and curate the data
 * not forget to add proper citations, acknowledge the authors

In the app:

 * onbuild-time, from these TSV files, generate a JSON/TS file containing all the data

 * on runtime, `import` the generated JSON/TS file in the app. Merge data into the app state.

 * make sure the generation occurs on TSV files change

Related:
 - https://github.com/neherlab/covid19_scenarios/issues/24

**Comment by rneher** [comment]
I think one should be closed. it is mostly obsolete.

**Comment by nnoll** [comment]
I agree with Richard.
