### ISSUE TITLE
french parser has multiple lines per day in .tsv

### ISSUE THREAD

**Issue by noleti** [neherlab/covid19_scenarios_data#41]
The french parser currently adds multiple rows for the same date, e.g. in `case-counts/Europe/Western Europe/France/Nouvelle-Aquitaine.tsv`. From a quick first look at the source, there might be county data below the state data, and each county adds a different line? I don't think the issue is from the store_data code, it seems to be in the dict before that function is called.

**Comment by rneher** [comment]
Yes, I noticed this too. The source is more of a line list of reports than a table. I added an adhoc catch to make sure the numbers are increases with time, but it would be good to make this more robust. @aschelch any ideas?

**Comment by aschelch** [comment]
Oh right, did not noticed. I'm on it ;)
