### ISSUE TITLE
Initial Condition JSON needs to read out location of scenarios.

### ISSUE THREAD

**Issue by nnoll** [neherlab/covid19_scenarios_data#56]
Before the app took care of the dispatch for whether a region was in the northern or southern hemisphere which helped to set the seasonal peak of the epidemic. Here, we have hard-coded in January. We need a way to input this data in automatically to correctly seed the JSON.

**Comment by noleti** [comment]
You mean it should be provided in `population.json`, put in there by `generate_data.py`? That script could pull a rough localization out of the country's `Area` in `country codes`. We would just require a lookup tables translating `Areas` into regions. Is this understanding correct? What name and value should the entry for this in population.json have? e.g., `[{"name": "Switzerland", "data": {"region": "Europe", ...}}]`, or "region": "Moderate/North"? For the lookup table, is there a reference? I.e. is Italy in `Moderate/North`? North refers to hemisphere, correct?

**Comment by noleti** [comment]
I created https://github.com/neherlab/covid19_scenarios_data/pull/57 now, please check if this is what you had in mind

**Comment by nnoll** [comment]
@noleti, this looks great. You're understanding is correct, we would pull it from country_codes provided we have a lookup table of area code -> hemisphere. 

With this current schema we don't need to keep track of slow/moderate/fast as we are fitting the growth rates on case-counts now so this selection dropdown will be gone. The one thing we need to preserve is the expected seasonal peak of the seasonality of the virus - i.e. which month we expect transmission to peak. For the northern hemisphere this is January, for the southern hemisphere its July, and the tropics seasonal forcing is expected to be zero. This needs to be set accordingly in the json field. 

The corresponding data fields are found within the EpidemiologicalParams class in both the "peakMonth" field and "seasonalForcing" field. Let me know if this makes sense and you are willing/have time to get to this, if not I'll update your pull request and merge.

**Comment by noleti** [comment]
@nnoll I created a new PR (see above) which should address the issue correctly this time. I require the hemisphere to be specified in the populationData.tsv.

**Comment by noleti** [comment]
This was merged now, I'm closing the issue
